streamr-dev/streamr-client-java

src/integrationTest/groovy/com/streamr/client/StreamEndpointsSpec.groovy, src/main/java/com/streamr/client/StreamrClient.java, src/main/java/com/streamr/client/StreamrRESTClient.java, src/main/java/com/streamr/client/exceptions/InvalidSignatureException.java, src/main/java/com/streamr/client/utils/SignatureVerificationResult.java, src/main/java/com/streamr/client/utils/SigningUtil.java, src/main/java/com/streamr/client/utils/SubscribedStreamsUtil.java, src/test/groovy/com/streamr/client/utils/SigningUtilSpec.groovy, src/test/groovy/com/streamr/client/utils/SubscribedStreamsUtilSpec.groovy
Same feature that has already been done in the Javascript client:
- cache both positive and negative results instead of a set of strings (publishers)
- use `streams/id/publisher/address` when cache miss, update the cache and return result
=> use second endpoint when cache miss

.travis.yml
Currently the travis script waits for the `auth/login` page to come up, which is part of the old frontend and will be removed shortly. Change the endpoint to an API endpoint.
=> Future-proof EE wait condition

src/main/java/com/streamr/client/options/StreamrClientOptions.java, src/test/groovy/com/streamr/client/StreamrClientOptionsSpec.groovy
Noticed a small problem with using the library. Made a quick fix via GitHub file editor, so **this is untested**. Could you @mthambipillai pick it up from here: verify it's working and include it in the next release, thanks.
=> Enforce query string on ws endpoint

src/integrationTest/groovy/com/streamr/client/StreamrWebsocketSpec.groovy, src/main/java/com/streamr/client/StreamrClient.java, src/main/java/com/streamr/client/options/StreamrClientOptions.java, src/main/java/com/streamr/client/utils/OneTimeResend.java, src/main/java/com/streamr/client/utils/Subscriptions.java, src/test/groovy/com/streamr/client/StreamrClientSpec.groovy, src/test/groovy/com/streamr/client/TestWebSocketServer.java, src/test/groovy/com/streamr/client/TestingStreamrClient.java
If the node goes down, the client now tries to reconnect with a fixed interval. Once it is reconnected, it sends a new subscribe request for each subscription that was interrupted.
I also did some manual testing on some integration tests (killing `data-api` in the middle of the test)
=> init retry

src/main/java/com/streamr/client/utils/OrderedMsgChain.java, src/test/groovy/com/streamr/client/utils/OrderedMsgChainSpec.groovy
- Fixed an issue where `clearGap()` is not called if the `gapFillFailedHandler` throws
- Tweaked default behavior to log a warning and ignore the failure by continuing from the next message in queue.
Would be good to have tests & make the behavior configurable. I'll leave it to you @mthambipillai. Maybe it's best to merge this PR and continue on the technical debt in a separate one.
`engine-and-editor` has currently been hotfixed _with these changes in place_, although they are not yet published to Maven. So the sooner we get these into an actual release, the better.
=> Recover from failed gapfills

src/main/java/com/streamr/client/StreamrClient.java, src/test/groovy/com/streamr/client/StreamrClientSpec.groovy, src/test/groovy/com/streamr/client/TestWebSocketServer.java
StreamrClient was not re-connecting on a clean handshake close (`onClose`) but only on error (`onError`). Extracted re-connect logic into a method and then reused it in `onClose` callback. Added a small integration test to verify that client indeed re-connects and receives messages.
=> Add re-connecting to onClose event

src/main/java/com/streamr/client/utils/OrderedMsgChain.java, src/test/groovy/com/streamr/client/utils/OrderedMsgChainSpec.groovy
Quick fix to prevent the queue from growing totally without bound in `OrderedMsgChain`.
=> Limit the queue size in OrderedMsgChain

src/main/java/com/streamr/client/utils/OrderedMsgChain.java, src/main/java/com/streamr/client/utils/OrderingUtil.java, src/test/groovy/com/streamr/client/StreamrClientSpec.groovy, src/test/groovy/com/streamr/client/utils/OrderedMsgChainSpec.groovy
This PR attempts to add thread-safety to `OrderedMsgChain`. All public methods are now `synchronized` and the internal gapfill timer also synchronizes on the instance object, avoiding inconsistent state resulting from multiple threads mutating the state in parallel.
=> Make OrderedMsgChain thread-safe

.idea/modules/streamr-client-java.iml, .idea/modules/streamr-client-java_integrationTest.iml, .idea/modules/streamr-client-java_main.iml, .idea/modules/streamr-client-java_test.iml, src/main/java/com/streamr/client/StreamrClient.java, src/test/groovy/com/streamr/client/StreamrClientSpec.groovy
- IDEA file commits are intentional.
- Added test that reproduces the stack trace found on the latest comment of Jira ticket CORE-1912.
- Added the corresponding fix to method `publish`. When we are not connected, it will only `connect()` if `!userWantsToConnect`, i.e., we don't have an ongoing reconnect thread in the works.
=> CORE-1912: websocketclient objects are not reuseable

src/integrationTest/groovy/com/streamr/client/StreamrWebsocketSpec.groovy, src/main/java/com/streamr/client/StreamrClient.java, src/test/groovy/com/streamr/client/HistoricalSubscriptionSpec.groovy, src/test/groovy/com/streamr/client/StreamrClientSpec.groovy
Re-write the reconnection logic so that there is a task that gets executed every `reconnectRetryInterval` milliseconds. This task makes sure that the intended state `keepConnected` of StreamrClient is followed by either opening or closing the underlying websocket connection.
=> JAVA-8: Re-write reconnection logic

src/main/java/com/streamr/client/options/StreamrClientOptions.java, src/test/groovy/com/streamr/client/StreamrClientOptionsSpec.groovy
Running the following code
```java
import com.streamr.client.MessageHandler;
import com.streamr.client.StreamrClient;
import com.streamr.client.protocol.message_layer.StreamMessage;
import com.streamr.client.rest.Stream;
import com.streamr.client.subs.Subscription;
import java.io.IOException;
public class Main {
public static void main(String[] args) throws IOException {
StreamrClient client = new StreamrClient();
Stream stream = client.getStream("7wa7APtlTq6EC5iTCBy6dw");
Subscription sub = client.subscribe(stream, new MessageHandler() {
@Override
public void onMessage(Subscription sub, StreamMessage message) {
System.out.println(message.getParsedContent());
}
});
}
}
```
shows that streamr-client-java sends a WS request with controlLayerVersion=1 even though it expects responses from …
=> Update versions in url

src/main/java/com/streamr/client/StreamrRESTClient.java
To support custom stream IDs (e.g. sandbox/foo/bar)
=> NET-62: Encode API path parameters

src/main/java/com/streamr/client/StreamrRESTClient.java
Name field is optional in POST /stream endpoint, remove the assertion check.
=> NET-66: Can create stream without "name" field

build.gradle
- Remove unused main-class and class-path attribute's
- Add implementation-version attribute
=> NET-75: Fix jar files manifest

.travis.yml
Currently build is failing because we try to stop a service that doesn't exist.
Bridge_collected was a service in streamr-docker-dev. It was removed from streamr-docker-dev earlier. See https://github.com/streamr-dev/streamr-docker-dev/commit/bd5278fe416f4b2f01758b11ab47088896602b49
=> Fix Travis build: remove bridge_collected

build.gradle
It's not used and commons lang 3 is available.
=> NET-104: Remove commons lang 2 dependency

build.gradle, src/integrationTest/groovy/com/streamr/client/dataunion/DataUnionClientTest.java
- This reverts commit bfa1fa4a5598cc2f8c772f0a0762ba44b8feadf6.
- Disable DataUnionClienTest now that it is being fixed
=> Revert "Bump cache2kVersion from 1.6.0.Final to 2.0.0.Final (#107)"

src/integrationTest/groovy/com/streamr/client/StreamEndpointsSpec.groovy, src/main/java/com/streamr/client/StreamrRESTClient.java, src/main/java/com/streamr/client/rest/StorageNode.java, src/main/java/com/streamr/client/rest/Stream.java, src/main/java/com/streamr/client/rest/StreamPart.java, src/main/java/com/streamr/client/utils/Address.java, src/main/java/com/streamr/client/utils/AddressJsonAdapter.java, src/main/java/com/streamr/client/utils/HttpUtils.java, src/test/groovy/com/streamr/client/utils/AddressJsonAdapterSpec.groovy
Added methods to storage node query/modification:
- `addStreamToStorageNode`
- `removeStreamToStorageNode`
- `getStorageNodes`
- `getStreamPartsByStorageNode`
The methods use new entity classes: `StorageNode` and `StreamPart`. Both are currently minimal without any no business logic. We'll add more methods to the classes in the future.
Added also new `AddressJsonAdapter` to support the JSON serialization/deserialization of `Address` class.
=> NET-178: Storage node endpoints

src/integrationTest/groovy/com/streamr/client/StreamEndpointsSpec.groovy, src/main/java/com/streamr/client/utils/Address.java, src/main/java/com/streamr/client/utils/KeyExchangeUtil.java, src/main/java/com/streamr/client/utils/SigningUtil.java, src/test/groovy/com/streamr/client/TestWebSocketServer.java, src/test/groovy/com/streamr/client/protocol/ResendFromRequestAdapterSpec.groovy, src/test/groovy/com/streamr/client/protocol/ResendRangeRequestAdapterSpec.groovy, src/test/groovy/com/streamr/client/protocol/StreamMessageExamples.groovy, src/test/groovy/com/streamr/client/protocol/StreamMessageV30AdapterSpec.groovy, src/test/groovy/com/streamr/client/protocol/StreamMessageV31AdapterSpec.groovy, src/test/groovy/com/streamr/client/protocol/StreamMessageV32AdapterSpec.groovy, src/test/groovy/com/streamr/client/protocol/StreamrSpecification.groovy, src/test/groovy/com/streamr/client/utils/AddressSpec.groovy, src/test/groovy/com/streamr/client/utils/OrderedMsgChainSpec.groovy, src/test/groovy/com/streamr/client/utils/SigningUtilSpec.groovy
Added validation to `Address` constructor: an invalid string throws an `IllegalArgumentException`.
Address.toString() returns the Ethereum address in checksum case (good format for the user interfaces etc.) In protocol level we sometimes need the address in lowercase format. That's why the internal format is in lowercase, and there is a `toLowerCaseString()` accessor to get that format efficiently.
=> Address validation and checksum

README.md, client/src/integrationTest/groovy/com/streamr/client/rest/StreamEndpointsSpec.groovy, client/src/main/java/com/streamr/client/Streamr.java, client/src/main/java/com/streamr/client/StreamrClient.java, client/src/main/java/com/streamr/client/rest/StorageNode.java, client/src/main/java/com/streamr/client/rest/StreamrRestClient.java
Added constants StorageNode.STREAMR_GERMANY and StorageNode.STREAMR_DOCKER_DEV. The values are instances of StorageNode class.
Fixed also typo in method `removeStreamFromStorageNode` name.
=> NET-286: Storage node constants

README.md, client/src/integrationTest/groovy/com/streamr/client/rest/StreamEndpointsSpec.groovy, client/src/integrationTest/java/com/streamr/client/rest/StreamrRestClientTest.java, client/src/main/java/com/streamr/client/rest/Json.java, client/src/main/java/com/streamr/client/rest/Stream.java, client/src/main/java/com/streamr/client/rest/StreamrRestClient.java, client/src/test/java/com/streamr/client/rest/JsonTest.java
The `id` parameter of `client.createStream` can  be a path (or full stream id, as previously). It will be prefixed with a lowercased Ethereum address derived from user's private key.
E.g. 
```
Stream proto = new Stream.Builder().withId("/foo/bar").createStream()
client.createStream(proto)
// -> creates 0xabcdeabcde123456789012345678901234567890/foo/bar
```
=> NET-235: Create stream by path
